[build]
  command = "npm ci && npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_DISABLE_ESLINT = "1"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Uncomment this if you need to handle specific redirects
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
